### ISSUE TITLE
How to if play from get intent? Because this method use array?

### ISSUE THREAD

**Issue by harunarrosyid** [ArezooNazer/AndroidVideoPlayer#1]
I have two string Link_video and Subtitle_video, can you help me to change code 

https://pastebin.com/raw/dCMD5Nhe

the array list to use string from intent?

**Comment by ArezooNazer** [comment]
I'm not sure what is your problem exactly, but if you want to get a list of videos from an intent you can wrap your data using a parcelable model:
``` 
@Parcelize
data class VideoSource(var video: List<SingleVideo>? = null) :Parcelable

@Parcelize
data class SingleVideo(var id: Int? = null,
                       var videoType: Int? = 0,
                       var videoUrl: String? = null,
                       var subtitles: List<SubtitleEntity>? = null,
                       //and other data you may need ) : Parcelable
```
then send your videos data (including their subtitles) to PlayerActivity using an intent:

```
val intent = Intent(activity, PlayerActivity::class.java)
intent.putExtra(VIDEO_SOURCE, videoSource)
startActivity(intent)
```
