### ISSUE TITLE
gradle implementation?

### ISSUE THREAD

**Issue by fukemy** [ArezooNazer/AndroidVideoPlayer#10]
Hi, thanks for great lib, can you publish your lib? THanks so much

**Comment by ArezooNazer** [comment]
Thanks, @fukemy. Since the Exoplayer project is deprecated now, I highly suggest that you migrate or use the new library (Media3)

> This is the last planned release of the com.google.android.exoplayer2 artifacts. This project is now deprecated. All users should migrate to androidx.media3 (which contains the same ExoPlayer code). See [the migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) for more details, including a script to help with the migration. [link](https://github.com/google/ExoPlayer/releases/tag/r2.19.1)

p.s: I planned to update this repository and migrate to Media3, but it may not happen soon.

**Comment by fukemy** [comment]
thanks bro, I will wait for you <3
