### ISSUE TITLE
Stop and release player function

### ISSUE THREAD

**Issue by arnoudkooi** [ArezooNazer/AndroidVideoPlayer#8]
Is there a supported way to stop and release all players?
Now when I step back it keeps playing

**Comment by ArezooNazer** [comment]
If you are using multiple players, please check this [link](https://github.com/google/ExoPlayer/issues/273), I recommend using a single player.

You can pause or release the player in onPause or onStop of the PlayerActivity.

**Comment by arnoudkooi** [comment]
That worked, thank you!
Would you happen to know if it is possible to capture the event when a live stream ends?

**Comment by ArezooNazer** [comment]
yes, you can use Exoplayer event listener:

https://exoplayer.dev/listening-to-player-events.html
